In [329]:
import pandas as pd
import numpy as np

In [330]:
df = pd.read_csv("owid-co2-data.csv")


print(f"Size of data: {df.shape}")

Size of data: (50411, 79)

In [331]:
df.head(n=3)

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560,,0.0,0.0,,,,...,,,,,,,,,,
1,Afghanistan,1751,AFG,,,0.0,,,,,...,,,,,,,,,,
2,Afghanistan,1752,AFG,,,0.0,,,,,...,,,,,,,,,,

In [332]:
colums = df.columns 

# We first inspect if the column names are formatted with no extra spacings around it
try:
    # should print 1751
    print(df.at[1, 'year'])
except KeyError:
    print("No column name found!")

No column name found!

In [333]:
# we see that the cells have extra spaces, making data processing difficult
# therefore we have to rename the columns
for col in colums:
    c = col.strip()
    df.rename(columns={col: c}, inplace=True)
    
columns = df.columns
print("Renamed columns!")

try:
    # should print 1751
    print(df.at[1, 'year'])
except KeyError:
    print("No column name found!")

Renamed columns!
1751

In [334]:
# check the same with the cell values
# from inspection we see that blank spaces are filled with spaces rather than an empty string

def is_empty(a_str):
    if type(a_str) == str: 
        if a_str.strip() == '':
            return 1
    else:
        return 0 

empty_strings_count = 0

for col in columns:
    empty_strings_count += (df[col].apply(lambda x: is_empty(x))).sum()

print(f"Missing value count: {empty_strings_count}")

Missing value count: 2105184.0

In [335]:

countries = df['country'].unique()
for country in countries[:3]:
    print(f"|{country}|")
    
# there are unnecessary spaces 
# so replace with nan


df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
df = df.replace(r'^\s*$', np.nan, regex=True)

print("\nRemoved spaces\n")
countries = df['country'].unique()
for country in countries[:3]:
    print(f"|{country}|")

|Afghanistan                             |
|Africa                                  |
|Africa (GCP)                            |

Removed spaces

|Afghanistan|
|Africa|
|Africa (GCP)|

In [ ]:
# due to the amount of missing values and considering this is historical data that does not make sense to fill with statistic like mean, 
# dropping the rows that are missing >90% of the values makes the most sense 
empty_strings_count = 0
df = df.drop(df[df.isna().mean(axis=1) > 0.90].index)

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
100,Afghanistan,1850,AFG,3752993,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7.544802665710449,0.6289909482002258,NaN,NaN
101,Afghanistan,1851,AFG,3767956,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,0.15823374688625336,1.166808601738012e-06,1.6955069668256328e-06,2.9650570922967745e-06,1.0274136741372786e-07,7.608335494995117,0.6328009963035583,NaN,NaN
102,Afghanistan,1852,AFG,3783940,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,0.1569128930568695,2.3405787032970693e-06,3.4068980312440544e-06,5.955002961854916e-06,2.0752621310293762e-07,7.668357849121094,0.636613130569458,NaN,NaN
103,Afghanistan,1853,AFG,3800954,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,0.15652798116207123,3.5213199680583784e-06,5.133980721439002e-06,8.969567716121674e-06,3.1426708346771193e-07,7.727762699127197,0.6404255032539368,NaN,NaN
104,Afghanistan,1854,AFG,3818038,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,0.1557130664587021,4.7090425141504966e-06,6.8763088165724184e-06,1.2008194971713237e-05,4.228431293995527e-07,7.785914421081543,0.6442371606826782,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,Albania,1995,ALB,3258573,11600732968,0.10317699611186981,0.03166324645280838,2.0890650749206543,0.16525912284851074,8.590221405029297,...,NaN,0.036507342010736465,0.00016385092749260366,0.0002003203408094123,0.0003895119880326092,2.5340721549582668e-05,7.302267074584961,2.946129322052002,0.434062123298645,20.777816772460938
871,Albania,1996,ALB,3245680,12468867839,0.10490000247955322,0.03231988474726677,2.017508029937744,-0.07155712693929672,-3.4253180027008057,...,NaN,0.03617753088474274,0.00016531474830117077,0.00020111798949074,0.000392299669329077,2.5866924261208624e-05,6.818369388580322,2.870147228240967,0.8774032592773438,43.48945617675781
872,Albania,1997,ALB,3229665,11020137102,0.05176100134849548,0.01602673903107643,1.5430090427398682,-0.474498987197876,-23.519062042236328,...,NaN,0.035750117152929306,0.00016601635434199125,0.0002016908401856199,0.000394069793401286,2.6362597054685466e-05,5.991156578063965,2.352060317993164,0.6491497755050659,42.07038116455078
873,Albania,1998,ALB,3210134,12026242682,0.04355200007557869,0.013567035086452961,1.754709005355835,0.21169999241828918,13.719940185546875,...,NaN,0.03529931232333183,0.00016585183038841933,0.00020241779566276819,0.00039514657692052424,2.687696360226255e-05,6.2194719314575195,2.5675690174102783,0.6784830093383789,38.666412353515625
874,Albania,1999,ALB,3188598,13673692880,0.05505000054836273,0.01726464182138443,2.9861960411071777,1.2314870357513428,70.18183135986328,...,NaN,0.03490595519542694,0.00016567413695156574,0.00020360357302706689,0.00039666960947215557,2.7391899493522942e-05,7.263838768005371,3.7993853092193604,0.7216862440109253,24.167409896850586